### ISSUE TITLE
Can not run

### ISSUE THREAD

**Issue by turingking** [yongjhih/docker-android-studio#6]
$ sudo docker-compose up android-studio-stable    

WARNING: The ANDROID_HOME variable is not set. Defaulting to a blank string.
Creating androidstudio_android-studio-stable_1 ... 
Creating androidstudio_android-studio-stable_1 ... error
ERROR: for androidstudio_android-studio-stable_1  Cannot create container for service android-studio-stable: b'create .: volume name is too short, names should be at least two alphanumeric characters'
ERROR: for android-studio-stable  Cannot create container for service android-studio-stable: b'create .: volume name is too short, names should be at least two alphanumeric characters'
ERROR: Encountered errors while bringing up the project.

**Comment by mbrechet** [comment]
Hi, you should specify an environment variable ANDROID_HOME in your system to mpa ANDROID_HOME of the container

Regards

**Comment by turingking** [comment]
@mbrechet Thanks
